[build]
builder = "DOCKERFILE"
dockerfilePath = "n8n/Dockerfile"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "n8n"
icon = "🤖"

[[services.domains]]
domain = "${RAILWAY_PUBLIC_DOMAIN}"

[environments.production]
WEBHOOK_URL = "https://${RAILWAY_PUBLIC_DOMAIN}/webhook/haiku-chat"
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "https"
N8N_EDITOR_BASE_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
GENERIC_TIMEZONE = "UTC"